<strong><?php echo __('Vendor(s)'); ?></strong>
<?php foreach ($block->getVendors() as $vendor) : ?>
    <div class = "row">
    <div class = "col-sm-6 col-md-3">
    <div class = "thumbnail">
        <img src = "<?php echo $block->getImageUrl($vendor->getIcon()); ?>" alt = "<?php echo $vendor->getName(); ?>" style="max-height: 50px; max-width: 50px;">
    </div>
    </div>
    </div>

<?php endforeach; ?>